### ISSUE TITLE
when roslaunch vehicle_simulator system_real_robot.launch, REQUIRED process [terrainAnalysis-8] has died!

### ISSUE THREAD

**Issue by Zhangxiaof001** [HongbiaoZ/autonomous_exploration_development_environment#3]
When i roslaunch vehicle_simulator system_real_robot.launch, the following problem will occur . 
![error1](https://user-images.githubusercontent.com/41658567/139613163-2e7463a3-206a-405e-857b-242b346e53ba.png)
I tried two computers and they all have the same problem. 
If remove 
![error2](https://user-images.githubusercontent.com/41658567/139613944-c3ffc10a-eb54-4cc2-adce-9f19aebf07f3.png)
from the launch file, no such problem, can launch success.

**Comment by Zhangxiaof001** [comment]
if roslaunch vehicle_simulator system_indoor.launch, or other simulation environments, the same following problem will occur. 

Simulation started.

[ INFO] [1635734312.121594087]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1635734312.127999187]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...

Initialization complete.

Warning [parser.cc:950] XML Element[gravity], child of element[physics] not defined in SDF. Ignoring[gravity]. You may have an incorrect SDF file, or an sdformat version that doesn't support this element.
[ INFO] [1635734313.251412507]: waitForService: Service [/gazebo/set_physics_properties] is now available.
================================================================================REQUIRED process [terrainAnalysis-8] has died!
process has died [pid 8710, exit code -11, cmd /home/zxf/ZXF/autonomous_exploration_development_environment/devel/lib/terrain_analysis/terrainAnalysis __name:=terrainAnalysis __log:=/home/zxf/.ros/log/cc89146a-3abc-11ec-ab8f-287fcf743074/terrainAnalysis-8.log].
log file: /home/zxf/.ros/log/cc89146a-3abc-11ec-ab8f-287fcf743074/terrainAnalysis-8*.log
Initiating shutdown!
================================================================================
[realTimePlot-17] killing on exit
[rvizGA-18] killing on exit
[visualizationTools-16] killing on exit
[sensorScanGeneration-15] killing on exit
[vehicleSimulator-14] killing on exit
[spawn_robot-13] killing on exit
[spawn_lidar-12] killing on exit
[spawn_camera-11] killing on exit
[gazebo-10] killing on exit
[terrainAnalysisExt-9] killing on exit
[terrainAnalysis-8] killing on exit
[sensorTransPublisher-7] killing on exit
[ INFO] [1635734316.271356272, 0.280000000]: Camera Plugin: Using the 'robotNamespace' param: '/'
[ INFO] [1635734316.274618843, 0.290000000]: Camera Plugin (ns = /)  <tf_prefix_>, set to ""
[vehicleTransPublisher-6] killing on exit
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/gazebo_ros/spawn_model", line 239, in <module>
    exit_code = sm.run()
  File "/opt/ros/melodic/lib/gazebo_ros/spawn_model", line 185, in run
    self.args.gazebo_namespace)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/gazebo_ros/gazebo_interface.py", line 32, in spawn_urdf_model_client
    resp = spawn_urdf_model(model_name, model_xml, robot_namespace, initial_pose, reference_frame)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 442, in __call__
    return self.call(*args, **kwds)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 530, in call
    raise rospy.exceptions.ROSInterruptException("node shutdown interrupted service call")
rospy.exceptions.ROSInterruptException: node shutdown interrupted service call

Exploration metrics and vehicle trajectory are saved in 'src/vehicle_simulator/log'.

[pathFollower-5] killing on exit
[localPlanner-4] killing on exit
[diagnostic_aggregator-3] killing on exit
[ps3_joy-2] killing on exit
[ INFO] [1635734316.547719780, 0.310000000]: Physics dynamic reconfigure ready.
Traceback (most recent call last):
  File "/home/zxf/ZXF/autonomous_exploration_development_environment/src/visualization_tools/scripts/realTimePlot.py", line 112, in <module>
    listener()
  File "/home/zxf/ZXF/autonomous_exploration_development_environment/src/visualization_tools/scripts/realTimePlot.py", line 77, in listener
    r.sleep()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/timer.py", line 103, in sleep
    sleep(self._remaining(curr_time))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/timer.py", line 165, in sleep
    raise rospy.exceptions.ROSInterruptException("ROS shutdown request")
rospy.exceptions.ROSInterruptException: ROS shutdown request

[gazebo-10] escalating to SIGTERM
[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done

**Comment by Zhangxiaof001** [comment]
solution : fix terrainAnalysis.cpp code ,
![1](https://user-images.githubusercontent.com/41658567/140270573-03178b1b-9994-4182-995e-e2576bc81787.png)
and fix terrainAnalysisExt.cpp code
![2](https://user-images.githubusercontent.com/41658567/140270639-22775120-4a48-4d99-b24e-6fd43c4fa871.png)
